name: Trivy Image Scan (Cloud Security)

on:
  workflow_dispatch:
  push:
    branches: [ "main" ]

jobs:
  trivy-image-scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build Docker image
        run: |
          docker build -t pygoat:latest .

      - name: Run Trivy Image scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          #scan-type: "image"
          image-ref: "pygoat:latest"
          severity: "CRITICAL,HIGH"
          format: "sarif"
          output: "trivy-scan.sarif"
          exit-code: "0"
        # env:
        #   TRIVY_SKIP_DB_UPDATE: true
        #   TRIVY_SKIP_JAVA_DB_UPDATE: true

      - name: Download Trivy Scan Report Report
        uses: actions/upload-artifact@v4
        with:
          name: trivy-scan
          path: trivy-scan.sarif
